/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { StageService } from "../stage.service";
import { StageCreateInput } from "./StageCreateInput";
import { Stage } from "./Stage";
import { StageFindManyArgs } from "./StageFindManyArgs";
import { StageWhereUniqueInput } from "./StageWhereUniqueInput";
import { StageUpdateInput } from "./StageUpdateInput";
import { SectionFindManyArgs } from "../../section/base/SectionFindManyArgs";
import { Section } from "../../section/base/Section";
import { SectionWhereUniqueInput } from "../../section/base/SectionWhereUniqueInput";

export class StageControllerBase {
  constructor(protected readonly service: StageService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Stage })
  async createStage(@common.Body() data: StageCreateInput): Promise<Stage> {
    return await this.service.createStage({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        numberField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Stage] })
  @ApiNestedQuery(StageFindManyArgs)
  async stages(@common.Req() request: Request): Promise<Stage[]> {
    const args = plainToClass(StageFindManyArgs, request.query);
    return this.service.stages({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        numberField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Stage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async stage(
    @common.Param() params: StageWhereUniqueInput
  ): Promise<Stage | null> {
    const result = await this.service.stage({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        numberField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Stage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateStage(
    @common.Param() params: StageWhereUniqueInput,
    @common.Body() data: StageUpdateInput
  ): Promise<Stage | null> {
    try {
      return await this.service.updateStage({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          numberField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Stage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteStage(
    @common.Param() params: StageWhereUniqueInput
  ): Promise<Stage | null> {
    try {
      return await this.service.deleteStage({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          numberField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/sections")
  @ApiNestedQuery(SectionFindManyArgs)
  async findSections(
    @common.Req() request: Request,
    @common.Param() params: StageWhereUniqueInput
  ): Promise<Section[]> {
    const query = plainToClass(SectionFindManyArgs, request.query);
    const results = await this.service.findSections(params.id, {
      ...query,
      select: {
        content: true,
        createdAt: true,
        id: true,

        stage: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/sections")
  async connectSections(
    @common.Param() params: StageWhereUniqueInput,
    @common.Body() body: SectionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sections: {
        connect: body,
      },
    };
    await this.service.updateStage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/sections")
  async updateSections(
    @common.Param() params: StageWhereUniqueInput,
    @common.Body() body: SectionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sections: {
        set: body,
      },
    };
    await this.service.updateStage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/sections")
  async disconnectSections(
    @common.Param() params: StageWhereUniqueInput,
    @common.Body() body: SectionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sections: {
        disconnect: body,
      },
    };
    await this.service.updateStage({
      where: params,
      data,
      select: { id: true },
    });
  }
}
